import React,{useState}from'react';
import{Link}from'react-router-dom';
import{surahs}from'./data';
import{themes,paths,stories}from'./learning-data';
import{surahGuide}from'./surah-guide';
import{VerseReference}from'./verse-balloon';
import'./learning.css';
const getSurah=n=>surahs.find(s=>s.number===n);
export function SurahLink({number,children}){const s=getSurah(number);return <Link className="learn-surah" to={`/surah/${s.id}/${s.slug}`}><span>{String(number).padStart(2,'0')}</span>{children||s.name}<b aria-hidden="true">↗</b></Link>}
const verseUrl=(n,v)=>`https://quran.com/${n}/${v}`;
export function ThemeExplorer({preview=false}){
 const[q,setQ]=useState(''),[group,setGroup]=useState('All');
 const filtered=themes.filter(t=>(group==='All'||t.group===group)&&`${t.title} ${t.description} ${t.passages.map(p=>`${getSurah(p.surah).name} ${p.surah} ${p.lesson}`).join(' ')}`.toLowerCase().includes(q.trim().toLowerCase()));
 const shown=preview?themes.filter(t=>['faith','hope','patience','trust','dua','peace','moderation','sincerity','justice'].includes(t.id)):filtered;
 return <section id="themes" className="section learning-section"><div className="section-head"><div><span className="eyebrow">A QUESTION. A THEME. A PLACE TO BEGIN.</span><h2>What would you like to understand?</h2><p className="learn-intro">Discover teachings across the Quran, with a starting passage and a question to carry into your day.</p></div>{preview&&<Link className="learn-all" to="/themes">Explore all {themes.length} themes →</Link>}</div>
 {!preview&&<><label className="learn-search"><span aria-hidden="true">⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search a theme, Surah or teaching…" aria-label="Search themes"/></label><div className="learn-filters" aria-label="Theme categories">{['All','Foundations','Heart','Daily life','Big questions'].map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g}</button>)}</div><p className="learn-results" role="status">{filtered.length} {filtered.length===1?'theme':'themes'} to explore</p></>}
 <div className="learn-theme-grid">{shown.map((t,i)=><article className={`learn-theme tone-${i%4}`} key={t.id}><div className="learn-card-top"><span className="learn-symbol" aria-hidden="true">{t.icon}</span><span className="learn-label">{t.group}</span></div><h3>{t.title}</h3><p>{t.description}</p><div className="learn-passages">{t.passages.map(p=><div className="learn-passage" key={`${p.surah}-${p.verses}`}><SurahLink number={p.surah}/><VerseReference surah={p.surah} verses={p.verses}/><small>{p.lesson}</small></div>)}</div><details className="learn-reflection"><summary>Pause & reflect</summary><p>{t.reflection}</p></details></article>)}</div>
 {!shown.length&&<div className="learn-empty"><h3>No themes found</h3><p>Try “patience”, “family” or a Surah name.</p><button onClick={()=>{setQ('');setGroup('All')}}>Reset search</button></div>}
 <p className="learn-note">These are starting points for study. A Surah can explore many themes; read the linked verses in context and open Tafsir on Quran.com to deepen your understanding.</p></section>
}
export function LearningPaths(){return <section id="learning-paths" className="section learning-section"><div className="section-head"><div><span className="eyebrow">ONE STEP AT A TIME</span><h2>A little direction for your journey</h2><p className="learn-intro">Choose a suggested reading path. Open a Surah, explore its visuals and reflect at your own pace.</p></div></div><div className="learn-path-grid">{paths.map((p,i)=><article className="learn-path" key={p.title}><span className="learn-path-number">0{i+1}</span><span className="eyebrow">{p.label}</span><h3>{p.title}</h3><p>{p.description}</p><ol>{p.surahs.map(n=><li key={n}><SurahLink number={n}/></li>)}</ol></article>)}</div></section>}
export function Stories(){return <section className="section learning-section story-section"><div className="section-head"><div><span className="eyebrow">STORIES THAT INVITE REFLECTION</span><h2>Learn through the journey</h2><p className="learn-intro">Explore selected Quranic accounts and the questions they raise about our own lives.</p></div></div><div className="learn-story-grid">{stories.map(s=><article className="learn-story" key={s.title}><span className="learn-story-mark" aria-hidden="true">✧</span><h3>{s.title}</h3><p>{s.description}</p><SurahLink number={s.surah}/><VerseReference surah={s.surah} verses={s.verses}>Read the account · {s.surah}:{s.verses} ↗</VerseReference></article>)}</div></section>}
export function StudyTools(){return <section id="study-tools" className="section learning-section"><div className="learn-study"><div><span className="eyebrow">SEE. READ. REFLECT. PRACTISE.</span><h2>Make understanding a daily habit</h2><p>Start with a visual, read the passage in context, then choose one lesson to practise. Return to the Quran with your questions and keep learning.</p><div className="learn-habit"><span>01 · Explore the visuals</span><span>02 · Read & listen</span><span>03 · Reflect & act</span></div></div><div className="learn-tools"><a href="https://quran.com" target="_blank" rel="noopener noreferrer"><strong>Read, listen & explore Tafsir ↗</strong><span>Translations, recitation and explanations on Quran.com</span></a><Link to="/themes"><strong>Find a teaching ↗</strong><span>Connect a question to a theme and its verses</span></Link><Link to="/surahs"><strong>Explore all 114 Surahs ↗</strong><span>Continue your visual learning journey</span></Link></div></div></section>}

export function SurahTable(){
 const[q,setQ]=useState(''),[storiesOnly,setStoriesOnly]=useState(false);
 const rows=surahs.map((s,i)=>({...s,...surahGuide[i]})).filter(s=>(!storiesOnly||s.accounts.length)&&`${s.number} ${s.name} ${s.meaning} ${s.message} ${s.accounts.join(' ')}`.toLowerCase().includes(q.trim().toLowerCase()));
 return <section id="surah-guide" className="section learning-section"><div className="section-head"><div><span className="eyebrow">THE WHOLE QURAN AT A GLANCE</span><h2>Every Surah. A starting point.</h2><p className="learn-intro">Compare verse counts, explore a core message and find selected prophetic stories and other Quranic accounts.</p></div><Link className="learn-all" to="/surahs">Browse visual cards →</Link></div><div className="learn-table-toolbar"><label className="learn-search"><span aria-hidden="true">⌕</span><input aria-label="Search Surah guide" placeholder="Search a Surah, message or story…" value={q} onChange={e=>setQ(e.target.value)}/></label><label className="learn-story-filter"><input type="checkbox" checked={storiesOnly} onChange={e=>setStoriesOnly(e.target.checked)}/> With selected stories</label></div><p className="learn-results" role="status">{rows.length} of 114 Surahs · On small screens, swipe the table to explore all columns.</p><div className="learn-table-wrap" tabIndex="0" role="region" aria-label="Surah overview table"><table className="learn-table"><caption>Surah learning guide — selected messages and narrative passages</caption><thead><tr><th scope="col">No.</th><th scope="col">Surah</th><th scope="col">Verses</th><th scope="col">Core message</th><th scope="col">Prophetic stories & other accounts</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><span className="learn-table-num">{s.id}</span></td><th scope="row"><Link to={`/surah/${s.id}/${s.slug}`}>{s.name} ↗</Link><small>{s.meaning}</small></th><td><span className="learn-verse-count">{s.ayahs}</span></td><td>{s.message}</td><td>{s.accounts.length?<ul>{s.accounts.map(a=><li key={a}><a href={`https://quran.com/${s.number}/${(a.match(/· ([0-9]+(?:–[0-9]+)?)/)?.[1]||'1').replace('–','-')}`} target="_blank" rel="noopener noreferrer">{a} ↗</a></li>)}</ul>:<span className="learn-no-story">No extended narrative highlighted</span>}</td></tr>)}</tbody></table>{!rows.length&&<div className="learn-empty"><h3>No Surahs found</h3><button onClick={()=>{setQ('');setStoriesOnly(false)}}>Reset filters</button></div>}</div><p className="learn-note">Core messages are brief study summaries, not exhaustive descriptions. Accounts include prophets and other people; a name appearing here does not imply prophethood. References are verse numbers within that Surah.</p></section>
}


export function SiteGuide(){return <section id="site-guide" className="section learning-section site-guide-section"><div className="section-head"><div><span className="eyebrow">NEW HERE? START HERE</span><h2>How to use Visual Quran</h2><p className="learn-intro">You do not need to know where to begin. Pick the kind of learning you want, follow the links and move at your own pace.</p></div><Link className="learn-all" to="/surahs">Start exploring →</Link></div><div className="guide-steps"><article className="guide-step"><span className="guide-number">01</span><h3>Choose a Surah</h3><p>Use <strong>Surahs</strong> or the Surah selector at the top. Open a Surah to see its visual slide journey.</p><div className="guide-example"><strong>Example</strong><span>Start with <Link to="/surah/001/al-fatihah">Al-Fatihah</Link> to see a short, simple visual journey.</span></div></article><article className="guide-step"><span className="guide-number">02</span><h3>Explore a topic</h3><p>Choose <strong>Themes</strong> when you have a question or life topic rather than a Surah in mind. Open a theme to find related passages and reflection prompts.</p><div className="guide-example"><strong>Example</strong><span>Looking for guidance about <Link to="/themes">patience, hope or trust</Link>? Start with a theme and follow its linked verses.</span></div></article><article className="guide-step"><span className="guide-number">03</span><h3>Use the Surah Table</h3><p>Open <strong>Surah Table</strong> for a quick overview of all 114 Surahs. Search by name, message or selected story and then open any Surah.</p><div className="guide-example"><strong>Example</strong><span>Want to compare Surahs before choosing one? Search the table and open the Surah that interests you.</span></div></article><article className="guide-step"><span className="guide-number">04</span><h3>Read, reflect and go deeper</h3><p>Inside a Surah, use the slide list or Previous/Next controls, open the visual full screen, and switch to Tamil when available. Then use the linked Quran.com references for deeper reading and Tafsir.</p><div className="guide-example"><strong>Example</strong><span>See a visual → read the passage in context → reflect on one lesson → return later and continue.</span></div></article></div><div className="guide-quick-links"><Link to="/surahs"><span>📖</span><strong>Browse Surahs</strong><small>Explore all 114</small></Link><Link to="/surah-table"><span>▦</span><strong>Surah Table</strong><small>Compare and search</small></Link><Link to="/themes"><span>✦</span><strong>Explore Themes</strong><small>Start with a question</small></Link><Link to="/dictionary"><span>⌕</span><strong>Quran Dictionary</strong><small>Search words and phrases</small></Link></div><p className="learn-note">Tip: If you are completely new, a simple path is <Link to="/surah/001/al-fatihah">Al-Fatihah</Link> → choose a theme → open the linked verses → return to the Surah when you are ready for more.</p></section>}

export function AboutContact({standalone=false}){return <section id="about" className="section learning-section"><div className="about-contact-grid"><article className="about-visual-quran"><span className="eyebrow">ABOUT VISUAL QURAN</span><h2>See the meaning.<br/>Carry it into your life.</h2><p>Visual Quran helps people of all ages explore the Quran through clear visuals, approachable study summaries and questions for reflection.</p><p>Browse a Surah, follow a theme or begin with a learning path. Our aim is to make it easier to connect reading with understanding and everyday practice.</p><div className="about-values"><span>Visual learning</span><span>Thoughtful reflection</span><span>Accessible exploration</span></div><Link className="learn-jump" to="/themes">Find your starting point →</Link></article><article id="contact" className="contact-visual-quran"><span className="eyebrow">CONTACT US</span><h2>Help us make learning better.</h2><p>Have a question, suggestion or a correction to share? We welcome feedback from readers, families and educators.</p><a className="contact-email" href="mailto:visualquran114@gmail.com"><span aria-hidden="true">✉</span><span>visualquran114@gmail.com</span></a><p className="contact-help">For a correction, please include the Surah name, verse or slide number, and a reference where possible.</p><a className="contact-cta" href="mailto:visualquran114@gmail.com">Get in touch ↗</a></article></div>{!standalone&&<p className="learn-note"><Link to="/about">Learn more about Visual Quran →</Link></p>}</section>}
