import React,{useEffect,useMemo,useState}from'react';
import{Link,useSearchParams}from'react-router-dom';
import{surahs}from'./data';
import{indexVerses,searchQuran}from'./quran-search-engine';
import'./quran-search.css';
const runtimeBase=(import.meta.env.VITE_APP_BASE_URL||'').replace(/\/$/,'');
const corpora=new Map();
function load(language){if(!corpora.has(language))corpora.set(language,fetch(`${runtimeBase}/search/quran-${language}.json.gz`).then(r=>{if(!r.ok)throw Error();return new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json()}).then(d=>{if(d.verses.length!==6236)throw Error();return d}).catch(e=>{corpora.delete(language);throw e}));return corpora.get(language)}
export function QuranSearch(){
 const[params,setParams]=useSearchParams(),query=params.get('q')||'',language=params.get('lang')?params.get('lang')==='ta'?'ta':'en':(()=>{try{return localStorage.getItem('visual-quran-language')==='ta'?'ta':'en'}catch{return'en'}})();
 const[draft,setDraft]=useState(query),[data,setData]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[related,setRelated]=useState(true),[surah,setSurah]=useState(0),[limit,setLimit]=useState(20);
 useEffect(()=>setDraft(query),[query]);
 useEffect(()=>{let active=true;setData(null);setError(false);Promise.all([load(language),load(language==='ta'?'en':'ta')]).then(([d,other])=>{if(active)setData({...d,index:indexVerses(d.verses,other.verses)})}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[language,retry]);
 useEffect(()=>setLimit(20),[query,language,related,surah]);
 const found=useMemo(()=>data?searchQuran(data.index,query,{related,surah}):{results:[],topics:[]},[data,query,related,surah]);
 const search=q=>setParams({q:q.trim(),lang:language});
 return <section className="quran-dictionary"><div className="dictionary-hero"><span className="eyebrow">QURAN SEMANTIC DICTIONARY</span><h1>A word. A question.<br/><em>A place to understand.</em></h1><p>Search the complete Quran by words, phrases or verse reference. Explore related passages alongside direct matches.</p><form onSubmit={e=>{e.preventDefault();search(draft)}} className="dictionary-search"><label className="sr-only" htmlFor="quran-query">Search Quran</label><input id="quran-query" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={160} placeholder="Try Ramadan, mercy, prayer, or 2:185…"/><button type="submit">Search →</button></form><div className="dictionary-examples">Try {['Ramadan','Firaun','Mercy','Prayer','பெற்றோர்','2:185'].map(q=><button key={q} onClick={()=>search(q)}>{q}</button>)}</div></div>
 <div className="dictionary-tools"><label>Translation <select aria-label="Search translation" value={language} onChange={e=>setParams({q:query,lang:e.target.value})}><option value="en">English</option><option value="ta">தமிழ்</option></select></label><label>Surah <select aria-label="Filter search by Surah" value={surah} onChange={e=>setSurah(Number(e.target.value))}><option value="0">All 114 Surahs</option>{surahs.map(s=><option value={s.number} key={s.number}>{s.number}. {s.name}</option>)}</select></label><label className="dictionary-related"><input type="checkbox" checked={related} onChange={e=>setRelated(e.target.checked)}/> Include related topics</label></div>
 <div className="dictionary-status" role="status">{error?<><p>Unable to load the Quran search index.</p><button onClick={()=>setRetry(n=>n+1)}>Try again</button></>:!data?<p>Loading the complete Quran index…</p>:query?<><h2>{found.results.length} verse{found.results.length!==1?'s':''} for “{query}”</h2>{found.topics.length>0&&related&&<p>Related topic: {found.topics.join(' · ')}</p>}{!found.results.length&&<p>Try a shorter word, another spelling, a verse reference, or a different translation.</p>}</>:<p>6,236 verses · Arabic, English & Tamil · Enter a search to begin.</p>}</div>
 <div className="dictionary-results">{found.results.slice(0,limit).map(v=>{const s=surahs.find(s=>s.number===v.surah);return <article className="dictionary-result" key={`${v.surah}:${v.verse}`}><div className="dictionary-result-head"><Link to={`/surah/${s.id}/${s.slug}`}>{s.name} <strong>{v.surah}:{v.verse}</strong></Link><span className={v.match==='Related topic'?'related-match':''}>{v.match}</span></div><p className="dictionary-arabic notranslate" lang="ar" dir="rtl" translate="no">{v.arabic}</p><p className={`dictionary-translation notranslate ${language==='ta'?'dictionary-tamil':''}`} lang={language} translate="no">{v.translation}</p>{v.footnotes&&<details className="dictionary-notes"><summary>Translation notes</summary><p lang={language} translate="no">{v.footnotes}</p></details>}<a className="dictionary-context" href={`https://quranenc.com/en/browse/${data.source.key}/${v.surah}/${v.verse}`} target="_blank" rel="noopener noreferrer">Read in context ↗</a></article>})}</div>{limit<found.results.length&&<button className="dictionary-more" onClick={()=>setLimit(n=>n+20)}>Show 20 more · {found.results.length-limit} remaining</button>}
 <p className="dictionary-note">Search matches Arabic, English and Tamil together while displaying your chosen translation. Cross-language matches are labelled. Tamil word beginnings and common name spellings are supported. Related results use a topic dictionary and selected study passages; they are a starting point, not an exhaustive interpretation. Translations express the meanings of the Quran.</p>{data&&<details className="dictionary-source"><summary>Source</summary><p>{data.source.title} · v{data.source.version} · QuranEnc.com</p><p>{data.source.description}</p><p>Index refreshed {new Date(data.updated).toLocaleDateString('en-GB')}. <a href={`https://quranenc.com/en/browse/${data.source.key}`} target="_blank" rel="noopener noreferrer">Translation source ↗</a></p></details>}
 </section>
}
